inputs:
    files:
        rho00: [
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/results/costhetastar_effycorrecteddist_charm_MB.root,
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/results/costhetastar_effycorrecteddist_charm_HM.root,
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/results/costhetastar_effycorrecteddist__beauty_MB.root,
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/results/costhetastar_effycorrecteddist_beauty_HM.root
        ]
        fractions: [
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/fraction/MB/finalbinning/DstarFraction_pp13TeV_MB_prompt.root,
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/fraction/HM/finalbinning/DstarFraction_pp13TeV_HM_prompt.root,
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/fraction/MB/finalbinning/DstarFraction_pp13TeV_MB_FD.root,
          /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/fraction/HM/finalbinning/DstarFraction_pp13TeV_HM_FD.root,
        ]
    ptbins:
        min: [5., 7., 10.]
        max: [7., 10., 20.]

output:
    file: /Users/fgrosa/cernbox/alice_work/analyses/Dstar_polarization/outputs/results/Rho00_corr # w/o extension
