input:
    sideband_dir: /home/daniel/alice/CharmingAnalyses/DKDpi/starting_selections/data/cf/
    specifier: KplusDminus

output: /home/daniel/alice/CharmingAnalyses/DKDpi/starting_selections/lambdaparam/kaons #wo extension

rebin: 3 # specifies the CF to use among those obtained with different rebinning of SE/ME distributions  

fit:
    method: legendre5
    xrange: [0., 3000.]
    yrange: [0.9, 2.4]
    parmin: [-3., -3., -3., -3., -3., -3.]
    parmax: [+2., +2., +2., +2., +2., +2.]

sidebands:
    combmethod: kAverage
    weightleftsb: 0.51
    weightrightsb: 0.49
